### ISSUE TITLE
screenshots: Here is a screenshot of Pale Moon running on "Linux"

### ISSUE THREAD

**Issue by MingcongBai** [wolfbeast/www.palemoon.org#1]
Just found out that the screenshots page only provided pictures of Pale Moon running on Windows, here is one of it running on Linux.

![screenshot_20160306_140651](https://cloud.githubusercontent.com/assets/5006263/13557034/0a174060-e3a5-11e5-9188-9213c85f8201.png)

**Comment by wolfbeast** [comment]
Which flavor of Linux, and which WM?

**Comment by MingcongBai** [comment]
AOSC OS with KDE Plasma 5.
2016年3月15日 18:23，"Moonchild" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
Oh BTW, you might want to think about asking for screenshots from other 3rd party Linux packages?

**Comment by wolfbeast** [comment]
Actually, if I'm going to use screenshots on the main website, they should be of official builds on common/directly-supported OSes. I appreciate you wanting to help but the screenshots should represent main-line Pale Moon :)

**Comment by MingcongBai** [comment]
The screenshot I've provided reflects an unaltered interface... oh well. It's fine.
